import { recruitingReport } from "@/lib/ats/reports";
import { stages } from "@/lib/ats/policy";
import { applicationStatusLabel } from "@/lib/format";
import { AdminHeader, StatCard, adminButtonSecondary } from "@/components/admin/ui";
import { control } from "@/components/admin/form";
export const dynamic = "force-dynamic";
export function ReportBars({ title, rows }: { title: string; rows: { label: string; value: number }[] }) {
  const max = Math.max(1, ...rows.map(r => r.value));
  return <section><h2 className="mb-4 text-sm font-medium text-ink-900">{title}</h2><div className="divide-y divide-paper-200 rounded-[4px] border border-paper-300 bg-white px-4">{rows.map(row => <div key={row.label} className="py-3"><div className="mb-2 flex justify-between gap-4 text-xs"><span>{applicationStatusLabel[row.label] ?? row.label}</span><span className="font-medium tabular-nums">{row.value}</span></div><div className="h-1 bg-paper-100"><div className="h-1 bg-ink-700" style={{ width: `${row.value / max * 100}%` }} /></div></div>)}{!rows.length && <p className="py-4 text-sm text-graphite-500">No data in this period.</p>}</div></section>;
}
export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ from?: string; to?: string; range?: string }> }) {
  const sp = await searchParams; const r = await recruitingReport(sp.from, sp.to, sp.range);
  const query = new URLSearchParams({ from: r.start.toISOString().slice(0,10), to: r.end.toISOString().slice(0,10) });
  return <><AdminHeader title="Recruiting reports" description="Applications, hiring progress and source performance." /><div className="space-y-6 p-5 sm:p-8"><form className="flex flex-wrap items-end gap-3"><label className="text-xs">Period<select name="range" defaultValue={sp.range ?? "30"} className={control}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="year">This year</option></select></label><label className="text-xs">Custom from<input name="from" type="date" defaultValue={sp.from} className={control} /></label><label className="text-xs">Custom to<input name="to" type="date" defaultValue={sp.to} className={control} /></label><button className={adminButtonSecondary}>Apply</button></form><div className="flex flex-wrap gap-2">{["applications", "candidates", "jobs", "interviews"].map(type => <a key={type} href={`/api/admin/export?type=${type}&${query}`} className={adminButtonSecondary}>Export {type}</a>)}</div><div className="grid gap-3 sm:grid-cols-3"><StatCard label="Job views" value={r.views} /><StatCard label="Avg. days to interview" value={r.timing?.interview?.toFixed(1) ?? "—"} /><StatCard label="Avg. days to hire" value={r.timing?.hire?.toFixed(1) ?? "—"} /></div><p className="text-xs text-graphite-500">Times use first recorded stage entry for applications submitted in this period. Stage reach counts historical entries, not just current stage. Job views count visits recorded since tracking was enabled.</p><div className="grid gap-6 xl:grid-cols-2"><ReportBars title="Hiring funnel · candidates reaching each stage" rows={[{ label: "Job views", value: r.views }, { label: "Applications", value: r.byStatus.reduce((n,s) => n+s.value,0) }, ...stages.filter(s => !["NEW","REJECTED"].includes(s)).map(s => ({ label: s, value: r.reached.find(v => v.label === s)?.value ?? 0 }))]} /><ReportBars title="Applications by current stage" rows={r.byStatus} /><ReportBars title="Applications by source" rows={r.bySource} /><ReportBars title="Applications by job" rows={r.byJob} /><ReportBars title="Applications over time (UTC)" rows={r.overTime} /></div></div></>;
}
