"use client";
import { useState } from "react";
import Link from "next/link";
import { WorkflowForm, WorkflowField } from "./WorkflowForm";
import { bulkCandidateAction } from "@/lib/ats/actions";
import { stages } from "@/lib/ats/policy";
import { applicationStatusLabel } from "@/lib/format";
export function BulkCandidates({ rows, staff, canAssign }: { rows: { id: string; name: string }[]; staff: { id: string; name: string }[]; canAssign: boolean }) {
  const [selected, setSelected] = useState<string[]>([]);
  const [kind, setKind] = useState("status");
  return <details className="mb-5 rounded-[4px] border border-paper-300 bg-white p-4"><summary className="cursor-pointer text-sm font-medium text-ink-900">Bulk actions · {selected.length} selected</summary><div className="mt-4 space-y-4"><label className="flex gap-2 text-xs"><input type="checkbox" checked={selected.length === rows.length && rows.length > 0} onChange={e => setSelected(e.target.checked ? rows.map(r => r.id) : [])} />Select this page</label><div className="grid max-h-48 gap-2 overflow-y-auto sm:grid-cols-2">{rows.map(row => <label key={row.id} className="flex gap-2 text-xs"><input type="checkbox" checked={selected.includes(row.id)} onChange={e => setSelected(e.target.checked ? [...selected, row.id] : selected.filter(id => id !== row.id))} />{row.name}</label>)}</div><label className="block text-xs">Action<select value={kind} onChange={e => setKind(e.target.value)} className="ml-3 rounded border border-paper-300 p-2"><option value="status">Change stage</option><option value="archive">Archive</option>{canAssign && <option value="assign">Assign recruiter</option>}<option value="email">Email candidates</option></select></label>{kind === "email" ? <div><p className="text-xs text-graphite-600">Review each candidate’s message before sending.</p>{rows.filter(r => selected.includes(r.id)).map(r => <Link key={r.id} href={`/admin/applications/${r.id}#email`} className="mt-2 block text-sm underline">Compose for {r.name}</Link>)}</div> : <WorkflowForm action={bulkCandidateAction} label={`Apply to ${selected.length} candidates`}><input type="hidden" name="kind" value={kind} />{selected.map(id => <input key={id} type="hidden" name="ids" value={id} />)}{kind === "status" && <WorkflowField name="status" label="Stage" options={stages.map(value => ({ value, label: applicationStatusLabel[value] }))} />}{kind === "assign" && <WorkflowField name="assignedTo" label="Recruiter" options={[{ value: "", label: "Unassigned" }, ...staff.map(s => ({ value: s.id, label: s.name }))]} />}{kind === "archive" && <p className="text-xs">Selected applications will be hidden from the active queue. Their history is retained and they can be restored.</p>}</WorkflowForm>}</div></details>;
}
