import Link from "next/link";
import { candidateWorkspace } from "@/lib/ats/data";
import { requireApplication } from "@/lib/ats/access";
import { permits, sources, interviewTypes, interviewStatuses } from "@/lib/ats/policy";
import { allowedTransitions } from "@/lib/ats/transitions";
import { applicationStatusLabel, offerStatusLabel, formatCurrency, formatDateTime, shortDate } from "@/lib/format";
import { canEditOffer, canSend, type OfferStatus } from "@/lib/offers/policy";
import { WorkflowForm, WorkflowField as Field } from "./WorkflowForm";
import { CandidateEmail } from "./CandidateEmail";
import { adminButtonSecondary, StatusPill } from "./ui";
const options = (values: readonly string[]) => values.map(value => ({ value, label: value }));
function Section({ title, id, children }: { title: string; id?: string; children: React.ReactNode }) {
  return <section id={id} className="rounded-[4px] border border-paper-300 bg-white p-5 sm:p-6"><h2 className="mb-4 text-[0.9375rem] font-medium text-ink-900">{title}</h2>{children}</section>;
}
export async function CandidateWorkspace({ id, jobTitle }: { id: string; jobTitle: string }) {
  const { admin, app } = await requireApplication(id);
  const w = await candidateWorkspace(id);
  const canEdit = permits(admin.role, "candidates");
  const nextInterview = [...w.meetings].reverse().find(i => ["Scheduled", "Rescheduled"].includes(i.status) && i.startsAt > new Date());
  return <div className="mt-5 space-y-5">
    <nav aria-label="Candidate workspace" className="flex flex-wrap gap-2 text-xs">{["notes", "interviews", "email", "activity"].map(tab => <a key={tab} href={`#${tab}`} className={adminButtonSecondary}>{tab[0].toUpperCase() + tab.slice(1)}</a>)}<Link href={`/admin/applications/${id}/resume`} className={adminButtonSecondary}>Resume viewer</Link></nav>
    {w.duplicates.length > 0 && <Section title="Potential duplicate applications"><p className="mb-3 text-sm text-graphite-600">This candidate may already exist. Review these records before taking action.</p>{w.duplicates.map(d => <Link key={d.id} href={`/admin/applications/${d.id}`} className="block py-1 text-sm underline">{d.firstName} {d.lastName} · {d.job} · {d.reference}</Link>)}</Section>}
    <div className="grid items-start gap-5 xl:grid-cols-2">
      <div className="space-y-5">
        {canEdit && <Section title="Recruiting details" id="stage"><div className="space-y-5">
          <WorkflowForm applicationId={id} kind="status" label="Update stage"><Field name="status" label="Current stage" value={app.status} options={[app.status, ...allowedTransitions(app.status, { hasEmployee: Boolean(w.employeeId) })].map(value => ({ value, label: applicationStatusLabel[value] }))} /></WorkflowForm>
          {w.employeeId && <p className="text-xs text-graphite-600">This candidate is now an employee, so their stage is locked.</p>}
          {app.status === "OFFER" && !w.employeeId && permits(admin.role, "manage") && <details><summary className="cursor-pointer text-xs text-graphite-600">Hired outside the system?</summary><div className="mt-3"><WorkflowForm applicationId={id} kind="status" label="Record hire"><input type="hidden" name="status" value="HIRED" /><input type="hidden" name="allowDirectHire" value="1" /><p className="text-xs text-graphite-500">Use only when the offer was made and accepted outside this platform. This is recorded in the audit log.</p></WorkflowForm></div></details>}
          <WorkflowForm applicationId={id} kind="profile" label="Save profile"><Field name="skills" label="Skills" value={app.skills} /><Field name="tags" label="Tags, separated by commas" value={app.tags.join(", ")} /><Field name="source" label="Application source" value={app.source || "Company Website"} options={options([...new Set([...sources, ...(app.source ? [app.source] : [])])])} /></WorkflowForm>
          <WorkflowForm applicationId={id} kind="star" label={w.starred ? "★ Unstar candidate" : "☆ Star candidate"}><input type="hidden" name="starred" value={w.starred ? "0" : "1"} /></WorkflowForm>
          <p className="text-xs text-graphite-600">Assigned to: {w.staff.find(s => s.id === app.assignedTo)?.name ?? "Unassigned"}</p>
          {permits(admin.role, "manage") && <WorkflowForm applicationId={id} kind="assign" label="Assign recruiter"><Field name="assignedTo" label="Recruiter" value={app.assignedTo ?? ""} options={[{ value: "", label: "Unassigned" }, ...w.staff.filter(s => permits(s.role, "candidates")).map(s => ({ value: s.id, label: s.name }))]} /></WorkflowForm>}
          <WorkflowForm applicationId={id} kind="archive" label={app.archivedAt ? "Restore application" : "Archive application"}><input type="hidden" name="restore" value={app.archivedAt ? "1" : "0"} /><p className="text-xs text-graphite-500">Archived applications retain their full history.</p></WorkflowForm>
          {app.status === "HIRED" && permits(admin.role, "employees") && <Link href={w.employeeId ? `/admin/employees/${w.employeeId}` : `/admin/employees/new?applicationId=${id}`} className={adminButtonSecondary}>{w.employeeId ? "Open employee" : "Create employee"}</Link>}
        </div></Section>}
        {permits(admin.role, "offers") && <Section title="Offer" id="offer">
          {w.offer ? <div className="space-y-3">
            <div className="flex flex-wrap items-center gap-3">
              <StatusPill status={w.offer.offer.status} label={offerStatusLabel[w.offer.offer.status]} />
              {w.offer.version && <span className="text-sm text-ink-900">{w.offer.version.jobTitle}</span>}
            </div>
            {w.offer.version && <p className="text-xs text-graphite-600">
              {w.offer.version.annualSalaryCents != null ? formatCurrency(w.offer.version.annualSalaryCents) : w.offer.version.hourlyRateCents != null ? `${formatCurrency(w.offer.version.hourlyRateCents)}/hr` : "No compensation set"}
              {" · "}Start {shortDate(w.offer.version.startDate)}
            </p>}
            <div className="flex flex-wrap gap-2">
              <Link href={`/admin/offers/${w.offer.offer.id}`} className={adminButtonSecondary}>View offer</Link>
              {canEditOffer(w.offer.offer.status as OfferStatus) && canEdit && <Link href={`/admin/offers/${w.offer.offer.id}/edit`} className={adminButtonSecondary}>Edit offer</Link>}
              {canSend(w.offer.offer.status as OfferStatus) && canEdit && <Link href={`/admin/offers/${w.offer.offer.id}`} className={adminButtonSecondary}>Send offer</Link>}
            </div>
          </div> : <>
            <p className="text-sm text-graphite-500">No offer yet.</p>
            {app.status === "OFFER" && canEdit && <Link href={`/admin/offers/new?applicationId=${id}`} className={`mt-3 inline-flex ${adminButtonSecondary}`}>Create offer letter</Link>}
          </>}
        </Section>}
        <Section title="Recruiter notes" id="notes"><p className="mb-4 text-xs text-graphite-500">Private to authorized recruiting staff. Most recent 100 notes.</p>
          {app.internalNotes && <p className="mb-4 whitespace-pre-wrap border-l-2 border-paper-300 pl-3 text-sm">{app.internalNotes}<span className="mt-1 block text-xs text-graphite-500">Legacy internal note</span></p>}
          <div className="space-y-4">{w.notes.map(({ note, author }) => <article key={note.id} className="border-b border-paper-200 pb-4"><p className="whitespace-pre-wrap text-sm text-ink-800">{note.note}</p><p className="mt-2 text-xs text-graphite-500">{author} · {formatDateTime(note.createdAt)}{note.updatedAt > note.createdAt ? " · Edited" : ""}</p>{(note.createdBy === admin.id || permits(admin.role, "manage")) && <details className="mt-2"><summary className="cursor-pointer text-xs underline">Edit or delete</summary><div className="mt-3 space-y-3"><WorkflowForm applicationId={id} kind="note" label="Save note"><input type="hidden" name="noteId" value={note.id} /><Field name="note" label="Note" value={note.note} multiline required /></WorkflowForm><WorkflowForm applicationId={id} kind="note" label="Delete this note"><input type="hidden" name="noteId" value={note.id} /><input type="hidden" name="intent" value="delete" /></WorkflowForm></div></details>}</article>)}</div>
          <div className="mt-4"><WorkflowForm applicationId={id} kind="note" label="Add note"><Field name="note" label="New internal note" multiline required /></WorkflowForm></div>
        </Section>
        <Section title="Interviews" id="interviews"><div className="space-y-5">{w.meetings.map(meeting => <article key={meeting.id} className="border-b border-paper-200 pb-4"><h3 className="text-sm font-medium">{meeting.type} · {meeting.status}</h3><p className="mt-1 text-xs text-graphite-600">{meeting.startsAt.toLocaleString("en-US", { timeZone: meeting.timezone })} – {meeting.endsAt.toLocaleTimeString("en-US", { timeZone: meeting.timezone })} ({meeting.timezone})</p><p className="mt-1 text-xs">Interviewers: {meeting.interviewers}</p>{meeting.location && <p className="mt-1 text-xs">{meeting.location}</p>}{meeting.meetingUrl && <a href={meeting.meetingUrl} target="_blank" rel="noopener noreferrer" className="mt-2 inline-block text-xs underline">Open meeting</a>}{meeting.notes && <p className="mt-2 whitespace-pre-wrap text-sm">{meeting.notes}</p>}
          {canEdit && <details className="mt-3"><summary className="cursor-pointer text-xs underline">Update / reschedule interview</summary><div className="mt-3"><WorkflowForm applicationId={id} kind="interview" label="Save interview"><input type="hidden" name="interviewId" value={meeting.id} /><Field name="type" label="Type" value={meeting.type} options={options(interviewTypes)} /><Field name="status" label="Status" value={meeting.status} options={options(interviewStatuses)} /><Field name="startsAt" label="Start (your local time)" type="datetime-local" value={meeting.startsAt.toISOString()} required /><Field name="endsAt" label="End (your local time)" type="datetime-local" value={meeting.endsAt.toISOString()} required /><Field name="interviewers" label="Interviewers" value={meeting.interviewers} required /><Field name="location" label="Location" value={meeting.location} /><Field name="meetingUrl" label="Meeting URL" type="url" value={meeting.meetingUrl} /><Field name="notes" label="Internal interview notes" value={meeting.notes} multiline /></WorkflowForm></div></details>}
        </article>)}{!w.meetings.length && <p className="text-sm text-graphite-500">No interviews scheduled.</p>}
          {canEdit && <details><summary className="cursor-pointer text-sm font-medium text-ink-900">Schedule interview</summary><div className="mt-4"><WorkflowForm applicationId={id} kind="interview" label="Schedule interview"><Field name="type" label="Interview type" options={options(interviewTypes)} /><input type="hidden" name="status" value="Scheduled" /><p className="text-xs text-graphite-500">Times use your device’s local time zone.</p><Field name="startsAt" label="Start" type="datetime-local" required /><Field name="endsAt" label="End" type="datetime-local" required /><Field name="interviewers" label="Interviewers" required /><Field name="location" label="Location" /><Field name="meetingUrl" label="Meeting URL" type="url" /><Field name="notes" label="Internal notes" multiline /></WorkflowForm></div></details>}
        </div></Section>
        <Section title="Hiring feedback"><div className="space-y-4">{w.feedback.map(({ feedback: f, author }) => <article key={f.id} className="border-b border-paper-200 pb-3"><p className="text-sm font-medium">{f.recommendation} · {f.rating}/5 overall</p><p className="mt-1 text-xs text-graphite-600">Technical {f.technical}/5 · Communication {f.communication}/5 · Team fit {f.teamFit}/5</p><p className="mt-2 whitespace-pre-wrap text-sm">{f.comments}</p><p className="mt-2 text-xs text-graphite-500">{author} · {formatDateTime(f.updatedAt)}</p></article>)}</div>{w.meetings.length > 0 && <div className="mt-4"><WorkflowForm applicationId={id} kind="feedback" label="Save feedback"><Field name="interviewId" label="Interview" options={w.meetings.filter(i => i.status !== "Cancelled").map(i => ({ value: i.id, label: `${i.type} · ${formatDateTime(i.startsAt)}` }))} />{[["rating", "Overall rating"], ["technical", "Technical skills"], ["communication", "Communication"], ["teamFit", "Team fit"]].map(([name, label]) => <Field key={name} name={name} label={label} required options={[{ value: "", label: "Choose a rating" }, ...[1,2,3,4,5].map(n => ({ value: String(n), label: `${n} / 5` }))]} />)}<Field name="recommendation" label="Recommendation" required options={[{ value: "", label: "Choose a recommendation" }, ...options(["Strong Hire", "Hire", "Maybe", "No Hire"])]} /><Field name="comments" label="Comments" multiline /></WorkflowForm></div>}</Section>
      </div>
      <div className="space-y-5">
        {canEdit && <Section title="Email candidate" id="email"><CandidateEmail applicationId={id} email={app.email} templates={w.templates} requestKey={crypto.randomUUID()} values={{ candidate_first_name: app.firstName, candidate_last_name: app.lastName, job_title: jobTitle, company_name: "Sohum Systems", interview_date: nextInterview?.startsAt.toLocaleDateString("en-US", { timeZone: nextInterview.timezone }) ?? "", interview_time: nextInterview ? `${nextInterview.startsAt.toLocaleTimeString("en-US", { timeZone: nextInterview.timezone })} ${nextInterview.timezone}` : "" }} /></Section>}
        <Section title="Email history">{w.messages.length ? <ul className="divide-y divide-paper-200">{w.messages.map(({ message: m, author }) => <li key={m.id} className="py-3"><p className="text-sm font-medium">{m.subject}</p><p className="mt-1 text-xs text-graphite-600">{m.status} · {author} · {formatDateTime(m.createdAt)}</p></li>)}</ul> : <p className="text-sm text-graphite-500">No messages sent.</p>}</Section>
        {canEdit && <Section title="Personal reminders"><ul className="space-y-3">{w.tasks.map(task => <li key={task.id}><p className="text-sm">{task.title} {task.completedAt ? "· Completed" : ""}</p><p className="text-xs text-graphite-500">Due {formatDateTime(task.dueAt)}</p>{!task.completedAt && <WorkflowForm applicationId={id} kind="reminder" label="Mark complete"><input type="hidden" name="reminderId" value={task.id} /></WorkflowForm>}</li>)}</ul><div className="mt-4"><WorkflowForm applicationId={id} kind="reminder" label="Add reminder"><Field name="title" label="Reminder" required /><Field name="dueAt" label="Due (your local time)" type="datetime-local" required /></WorkflowForm></div></Section>}
        <Section title="Activity timeline" id="activity"><p className="mb-4 text-xs text-graphite-500">Most recent 100 events. Full history remains in the audit log.</p><ol className="space-y-4">{w.activity.map(({ event: e, author }) => <li key={e.id} className="border-l-2 border-paper-300 pl-3"><p className="text-sm font-medium text-ink-900">{e.action.replace(/^ADMIN_/, "").replaceAll("_", " ").toLowerCase()}</p>{e.metadata?.from && e.metadata?.to ? <p className="mt-1 text-xs">{String(e.metadata.from)} → {String(e.metadata.to)}</p> : null}<p className="mt-1 text-xs text-graphite-500">{author ?? "System"} · {formatDateTime(e.createdAt)}</p></li>)}<li className="border-l-2 border-flame-500 pl-3"><p className="text-sm font-medium">Application submitted</p><p className="text-xs text-graphite-500">{formatDateTime(app.createdAt)}</p></li></ol></Section>
      </div>
    </div>
  </div>;
}
