import Link from "next/link";
import { actionCenter, upcomingInterviews } from "@/lib/ats/data";
import { formatDateTime } from "@/lib/format";
import { markNotificationAction } from "@/lib/ats/actions";
import { adminButtonSecondary } from "./ui";
export async function RecruitingActivity() {
  const [upcoming, actions] = await Promise.all([upcomingInterviews(), actionCenter()]);
  return <div className="grid gap-6 xl:grid-cols-2"><section><h2 className="mb-4 text-[0.9375rem] font-medium text-ink-900">Upcoming interviews</h2><ul className="divide-y divide-paper-200 rounded-[4px] border border-paper-300 bg-white">{upcoming.map(({ interview: i, name, job }) => <li key={i.id}><Link href={`/admin/applications/${i.applicationId}#interviews`} className="block px-4 py-3 hover:bg-paper-50"><p className="text-sm font-medium text-ink-900">{name} · {i.type}</p><p className="mt-1 text-xs text-graphite-600">{job}</p><p className="mt-1 text-xs text-graphite-500">{i.startsAt.toLocaleString("en-US", { timeZone: i.timezone })} ({i.timezone})</p></Link></li>)}{!upcoming.length && <li className="p-4 text-sm text-graphite-500">No upcoming interviews.</li>}</ul></section><section><h2 className="mb-4 text-[0.9375rem] font-medium text-ink-900">Needs attention</h2><ul className="divide-y divide-paper-200 rounded-[4px] border border-paper-300 bg-white">{actions.tasks.map(({ task, name }) => <li key={task.id}><Link href={`/admin/applications/${task.applicationId}`} className="block p-4 text-sm"><span className="font-medium">{task.title}</span><span className="mt-1 block text-xs text-graphite-500">{name} · Due {formatDateTime(task.dueAt)}</span></Link></li>)}{actions.feedbackDue.map((f, index) => <li key={`${f.id}-${index}`}><Link href={`/admin/applications/${f.id}#interviews`} className="block p-4 text-sm"><span className="font-medium">Interview feedback required</span><span className="mt-1 block text-xs text-graphite-500">{f.name} · {f.type}</span></Link></li>)}{!actions.tasks.length && !actions.feedbackDue.length && <li className="p-4 text-sm text-graphite-500">No pending reminders or interview feedback.</li>}</ul></section></div>;
}
export async function NotificationPanel() {
  const { alerts } = await actionCenter();
  return <details className="border-b border-paper-300 bg-white px-5 py-2 sm:px-8"><summary className="cursor-pointer text-xs font-medium text-ink-800">Notifications {alerts.length ? `(${alerts.length}${alerts.length === 20 ? "+" : ""} unread)` : "(0 unread)"}</summary><ul className="mt-2 max-h-80 divide-y divide-paper-200 overflow-y-auto">{alerts.map(alert => <li key={alert.id} className="flex flex-wrap items-center justify-between gap-2 py-3"><Link href={alert.href} className="text-sm underline">{alert.title}</Link><form action={markNotificationAction}><input type="hidden" name="id" value={alert.id} /><button className={adminButtonSecondary}>Mark read</button></form></li>)}{!alerts.length && <li className="py-3 text-xs text-graphite-500">You’re all caught up.</li>}</ul></details>;
}
