export const defaultEmailTemplates = [
  { name: "Application Received", subject: "Application received — {{job_title}}", body: "Hello {{candidate_first_name}},\n\nThank you for applying for the {{job_title}} position at {{company_name}}. Our recruiting team has received your application and will review it.\n\nBest regards,\nSohum Systems Recruiting" },
  { name: "Application Under Review", subject: "Your application — {{job_title}}", body: "Hello {{candidate_first_name}},\n\nYour application for {{job_title}} is under review. We will be in touch about next steps.\n\nBest regards,\nSohum Systems Recruiting" },
  { name: "Interview Invitation", subject: "Interview invitation — {{job_title}}", body: "Hello {{candidate_first_name}},\n\nWe would like to invite you to an interview for {{job_title}} on {{interview_date}} at {{interview_time}}.\n\nPlease confirm your availability.\n\nBest regards,\nSohum Systems Recruiting" },
  { name: "Interview Reminder", subject: "Interview reminder — {{job_title}}", body: "Hello {{candidate_first_name}},\n\nThis is a reminder of your interview for {{job_title}} on {{interview_date}} at {{interview_time}}. Please let us know if you need to reschedule.\n\nBest regards,\nSohum Systems Recruiting" },
  { name: "Next Interview Round", subject: "Next steps — {{job_title}}", body: "Hello {{candidate_first_name}},\n\nThank you for meeting with us. We would like to arrange the next interview round for {{job_title}}. Please share your availability.\n\nBest regards,\nSohum Systems Recruiting" },
  { name: "Offer", subject: "Next steps with Sohum Systems — {{job_title}}", body: "Hello {{candidate_first_name}},\n\nWe are pleased to discuss an offer for {{job_title}} with you. Our team will contact you with the details and next steps.\n\nBest regards,\nSohum Systems Recruiting" },
  { name: "Rejection", subject: "Update on your application — {{job_title}}", body: "Hello {{candidate_first_name}},\n\nThank you for your interest in {{company_name}} and for the time you invested in applying for {{job_title}}. We have decided to move forward with other candidates for this position. We appreciate your interest and wish you success in your search.\n\nBest regards,\nSohum Systems Recruiting" },
];
